spring:
  application:
    name: datingapp-user-service
  data:
    mongodb:
      database: datingapp-user-service-db
      port: 27017
      host: localhost

server:
  port: 9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

amqp.availableuser.exchange: availableuser.exchange
amqp.availableuser.routingkey: availableuser.routingkey

rabbitmq:
  addresses: localhost:5672
  adminAddresses: http://localhost:15672
  nodes: rabbit@localhost
  username: guest
  password: guest
  virtual_host: /
  useSSL: false
  sslProperties:
  ssl:
    keyStore:
    keyStorePassphrase:
    trustStore:
    trustStorePassphrase:
  channelCacheSize: 100




logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.springframework.amqp.rabbit.core.RabbitTemplate: INFO
    com.mintbeans.chat.service:
      MessagePublisher: INFO
      MessageSubscriber: INFO

datingapp.security.jwt.secret: V*l*k*O*n*R19--23